[package]
name = "sub"
version = "1.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]
edition = "2021"

[dependencies]
chumsky = "*"
clap = { version = "*", features = ["string"] }
lazy_static = "*"
regex = "*"
xdg = "*"
